describe('My First Test', () => {
  it('Visits the initial project page', () => {
    cy.visit('/')
    cy.contains('Fitnessfriends')
    cy.contains('Home')
    cy.contains('Create Post')
    cy.contains('View Post')
    cy.contains('Login')
    cy.contains('Signup')
  })
  it('Navigates to the homepage', () => {
    cy.contains('Home').click()
    cy.contains('Home')
    cy.contains('Fitnessfriends')
    cy.contains('Home')
    cy.contains('Create Post')
    cy.contains('View Post')
    cy.contains('Login')
    cy.contains('Signup')
    cy.contains('Global Fitness')  
  })
  it('Navigates to the Create Post page', () => {
    cy.contains('Create Post').click()
    cy.contains('Home')
    cy.contains('Fitnessfriends')
    cy.contains('Home')
    cy.contains('Create Post')
    cy.contains('View Post')
    cy.contains('Login')
    cy.contains('Signup')
    cy.contains('Global Fitness')  
  })
  it('Navigates to the View Post page', () => {
    cy.contains('View Post').click()
    cy.contains('Home')
    cy.contains('Fitnessfriends')
    cy.contains('Home')
    cy.contains('Create Post')
    cy.contains('View Post')
    cy.contains('Login')
    cy.contains('Signup')
    cy.contains('Global Fitness')  
  })
  it('Navigates to the Login page', () => {
    cy.contains('Login').click()
    cy.contains('Home')
    cy.contains('Fitnessfriends')
    cy.contains('Home')
    cy.contains('Create Post')
    cy.contains('View Post')
    cy.contains('Login')
    cy.contains('Signup')
    cy.contains('Global Fitness')  
  })
  it('Navigates to the Signup page', () => {
    cy.contains('Signup').click()
    cy.contains('Home')
    cy.contains('Fitnessfriends')
    cy.contains('Home')
    cy.contains('Create Post')
    cy.contains('View Post')
    cy.contains('Login')
    cy.contains('Signup')
    cy.contains('Global Fitness')  
  })
})
